In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

dataset = pd.read_csv('datasets/play_football.csv', sep = ",")

label = LabelEncoder()
dataset = dataset.apply(label.fit_transform)

dataset.columns = pd.read_csv('datasets/play_football.csv', sep = ",").columns

X = dataset.drop('Play', axis = 1)
Y = dataset['Play']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.4, random_state = 111)

clf = GaussianNB()
clf.fit(X_train,Y_train)

GaussianNB(priors=None)

In [2]:
clf.predict(X_test)

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1])

In [3]:
clf_pf = GaussianNB()
clf_pf.partial_fit(X_train, Y_train, np.unique(Y_train))

GaussianNB(priors=None)

In [4]:
clf_pf.predict(X_test)

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1])

In [5]:
np.unique(Y_test)

array([0, 1])

In [6]:
clf.class_prior_

array([ 0.35820896,  0.64179104])

In [7]:
clf.class_count_

array([  96.,  172.])

In [8]:
clf.theta_

array([[ 1.54166667,  1.26041667,  0.27083333,  0.53125   ],
       [ 0.8372093 ,  1.04069767,  0.63372093,  0.29069767]])

In [9]:
clf.sigma_

array([[ 0.31076389,  0.56759983,  0.19748264,  0.24902344],
       [ 0.63628989,  0.7483437 ,  0.23211871,  0.20619254]])

In [10]:
clf.score(X_test, Y_test)

0.78888888888888886