In [1]:
# Import 
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [2]:
# Load Dataset
X = pd.read_csv('datasets/titanic_train.csv')
X.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
# Dimensione
X.shape

(891, 12)

In [4]:
# Per selezionare le righe che hanno solo valori categorici uso la funzione
# 'df.select_dtypes() e includendo solo gli elementi di tipo 'object'
X_cat = X.select_dtypes(include = [object])
X_cat.head()

# Sostituisco i valori che presentano np.NaN con la stringa 'NaN'
X_cat = X_cat.fillna('NaN')

In [5]:
# Visualizzo la dimensione di questo sottoinsieme
X_cat.shape

(891, 5)

In [6]:
# Vedo le colonne utilizzando l'attributo 'df.columns'
X_cat.columns

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [7]:
# Creo un oggetto LabelEncoder e lo alleno per ogni features di X_cat

label = LabelEncoder()
X_label = X_cat.apply(label.fit_transform)
X_label.head()

Name  Sex  Ticket  Cabin  Embarked
0   108    1     523    146         3
1   190    0     596     81         0
2   353    0     669    146         3
3   272    0      49     55         3
4    15    1     472    146         3

In [8]:
# Prende una matrice di valori numeri e costruisce una colonna con la 'cardinalità'
# Ad esempio se una colonna ha due tipi di valori (2, 4 ad esempio) lo costrisce una matrice
# con due colonne '2' e '4' e per ogni riga inserirà 1 se il valore assunto in posizione è 2 o 4
# In altre parole è una versione più complessa di get_dummies ma a differenza di questo è utile quando
# si presentano dei dati nuovi nella stessa forma. Infatti dopo aver allenato 'OneHotEncoder' e possibile
# trasformare i nuovi valori

onehot = OneHotEncoder()
onehot.fit(X_label)
onehotlabels = onehot.transform(X_label).toarray()
onehotlabels

array([[ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.]])

In [9]:
# Si può notare la dimensione
onehotlabels.shape

(891, 1726)

In [10]:
# Il tipo restituito è una matrice
type(onehotlabels)

numpy.ndarray

In [11]:
# Indica il numero massimo di valori per ogni colonna
onehot.n_values_

array([891,   2, 681, 148,   4])

In [12]:
# Indica il range di ogni features. Per ogni features[i] viene mappata in features che vanno da
# 'features[i] a features[i+1]. Si può notare infatti che somma i valori di 'n_values_'
onehot.feature_indices_

array([   0,  891,  893, 1574, 1722, 1726])

In [13]:
# Ad esempio se uso una matrice costituta da [475,1 , 321, 103, 2] ritornerà
# In pratica, inserirà uno in quelle colonne, in modo molto semplice
matrix = [[475, 1, 321, 103, 2]]
onehot.transform(matrix).toarray()

array([[ 0.,  0.,  0., ...,  0.,  1.,  0.]])