In [1]:
# Ndarray è un array di oggetti n-dimensionale
import numpy as np

In [2]:
"""
numpy.arange

    Return evenly spaced values within a given interval.
    Values are generated within the half-open interval [start, stop)
    (in other words, the interval including start but excluding stop). 
    For integer arguments the function is equivalent to the Python built-in range function, 
    but returns an ndarray rather than a list.
    When using a non-integer step, such as 0.1, the results will often not be consistent.
    It is better to use linspace for these cases.

Parameters:
    start : number, optional
        Start of interval. The interval includes this value. The default start value is 0.
    stop : number
        End of interval. The interval does not include this value, 
        except in some cases where step is not an integer and floating point round-off affects the length of out.
    step : number, optional
    Spacing between values. For any output out, this is the distance between two adjacent 
    values, out[i+1] - out[i]. The default step size is 1. If step is specified, start must also be given.
    dtype : dtype
    The type of the output array. If dtype is not given, infer the data type from the other input arguments.
Returns:
    arange : ndarray
    Array of evenly spaced values.
    For floating point arguments, the length of the result is ceil((stop - start)/step). 
    Because of floating point overflow, this rule may result in the last element of out being greater than stop.
"""
array_arange = np.arange(3)
array_arange
array_arange_step = np.arange(start=2, stop = 15, step = 3)
array_arange_step

array([ 2,  5,  8, 11, 14])

In [3]:
"""
numpy.one
    Return a new array of given shape and type, filled with ones.

Parameters:
    shape : int or sequence of ints
            Shape of the new array, e.g., (2, 3) or 2.
    dtype : data-type, optional
            The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.
    order : {‘C’, ‘F’}, optional
            Whether to store multidimensional data in C- or Fortran-contiguous 
            (row- or column-wise) order in memory.
Returns:
    out : ndarray
    Array of ones with the given shape, dtype, and order.
"""
array_ones = np.ones(5)
array_ones
array_ones_int = np.ones(5, dtype=int)
array_ones_int
matrix_ones = np.ones((5,6))
matrix_ones
matrix_ones_int = np.ones((2,3), dtype=int)
matrix_ones_int
"""
numpy.ones_like
    Return an array of ones with the same shape and type as a given array.

Parameters:
    a : array_like
        The shape and data-type of a define these same attributes of the returned array.
    dtype : data-type, optional
        Overrides the data type of the result.
        New in version 1.6.0.
    order : {‘C’, ‘F’, ‘A’, or ‘K’}, optional
        Overrides the memory layout of the result. ‘C’ means C-order, 
        ‘F’ means F-order, ‘A’ means ‘F’ if a is Fortran contiguous, 
        ‘C’ otherwise. ‘K’ means match the layout of a as closely as possible.
        New in version 1.6.0.
    subok : bool, optional.
        If True, then the newly created array will use the sub-class type of ‘a’, 
        otherwise it will be a base-class array. Defaults to True.
Returns:
    out : ndarray
        Array of ones with the same shape and type as a.
"""
x = np.arange(6)
x = x.reshape((2,3))
array_ones_like = np.ones_like(x)
array_ones_like

"""
Le funzione zeros e zeros_like funzionano esattamente come ones e ones_like ma producono n-array 
di 0 invece che si 1
"""
array_zeros = np.zeros(5, dtype=float)
array_zeros
matrix_zeros = np.zeros((7,2))
matrix_zeros

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [4]:
"""
numpy.empty

    Return a new array of given shape and type, without initializing entries.

Parameters:
    shape : int or tuple of int
        Shape of the empty array
    dtype : data-type, optional
        Desired output data-type.
    order : {‘C’, ‘F’}, optional
        Whether to store multi-dimensional data in row-major (C-style) or column-major
        (Fortran-style) order in memory.
Returns:
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and order. 
        Object arrays will be initialized to None.
"""
array_empty = np.empty([2,4])
array_empty
array_empty_int = np.empty([3,3], dtype=int)
array_empty_int
"""
numpy.empty_like

    Return a new array with the same shape and type as a given array.

Parameters:
    a : array_like
        The shape and data-type of a define these same attributes of the returned array.
    dtype : data-type, optional
        Overrides the data type of the result.
        New in version 1.6.0.
    order : {‘C’, ‘F’, ‘A’, or ‘K’}, optional
        Overrides the memory layout of the result. ‘C’ means C-order, ‘F’ means F-order, 
        ‘A’ means ‘F’ if a is Fortran contiguous, ‘C’ otherwise.
        ‘K’ means match the layout of a as closely as possible.
        New in version 1.6.0.
    subok : bool, optional.
        If True, then the newly created array will use the sub-class type of ‘a’, 
        otherwise it will be a base-class array. Defaults to True.
Returns:
    out : ndarray
    Array of uninitialized (arbitrary) data with the same shape and type as a.
"""
a = ([1,2,3],[4,5,6])
array_empty_like = np.empty_like(a)
array_empty_like
b = ([1.,2.,3.],[4.,5.,6.])
array_empty_like_float = np.empty_like(b)
array_empty_like_float

array([[  4.64329861e-310,   0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000]])

In [5]:
"""
numpy.eye

    Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters:
    N : int
        Number of rows in the output.
    M : int, optional
        Number of columns in the output. If None, defaults to N.
    k : int, optional
        Index of the diagonal: 0 (the default) refers to the main diagonal,
        a positive value refers to an upper diagonal, and a negative value to a lower diagonal.
    dtype : data-type, optional
        Data-type of the returned array.
Returns:
    I : ndarray of shape (N,M)
    An array where all elements are equal to zero, except for the k-th diagonal, 
    whose values are equal to one.
"""
array_eye = np.eye(2, dtype=int)
array_eye
array_eye2 = np.eye(2,6,dtype=float)
array_eye2
semi_array_eye = np.eye(4, k=2, dtype=int)
semi_array_eye
"""
numpy.identity

    The identity array is a square array with ones on the main diagonal.

Parameters:
    n : int
        Number of rows (and columns) in n x n output.
    dtype : data-type, optional
        Data-type of the output. Defaults to float.
Returns:
    out : ndarray
    n x n array with its main diagonal set to one, and all other elements 0.
"""
array_identity = np.identity(n=4)
array_identity

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])