In [1]:
import numpy as np

array = np.arange(20)

In [2]:
"""
SINGLE ELEMENT INDEXING

    Single element indexing for a 1-D array is what one expects. 
    It work exactly like that for other standard Python sequences. 
    It is 0-based, and accepts negative indices for indexing from the end of the array.
"""
print('Elemento in posizione 2:',array[2])
print('Elemento in posizione -2:',array[-2])
"""
    Unlike lists and tuples, numpy arrays support multidimensional indexing for
    multidimensional arrays. That means that it is not necessary to separate each 
    dimension’s index into its own set of square brackets.
"""
array.shape = (5,4)
print('Matrice 5x4:\n',array)
print('Elemento in posizione (4,2):',array[4,2])
print('Elemento in posizione (3,-2):',array[3,-2])
"""
    Note that if one indexes a multidimensional array with fewer indices than dimensions,
    one gets a subdimensional array. 
"""
print('array[0]:', array[0])
print('array[-1]:', array[-1])
"""
    That is, each index specified selects the array corresponding to the rest of the dimensions selected. 
    In the above example, choosing 0 means that the remaining dimension of length 5 is being left 
    unspecified, and that what is returned is an array of that dimensionality and size. 
    It must be noted that the returned array is not a copy of the original, but points to the same values 
    in memory as does the original array. In this case, the 1-D array at the first position (0) is returned. 
    So using a single index on the returned array, results in a single element being returned. That is:
"""
print('array[2][1]:', array[2][1])

"""
    So note that x[0,2] = x[0][2] though the second case is more inefficient as a new temporary
    array is created after the first index that is subsequently indexed by 2.
    Note to those used to IDL or Fortran memory order as it relates to indexing.
    NumPy uses C-order indexing. That means that the last index usually represents the most rapidly 
    changing memory location, unlike Fortran or IDL, where the first index represents the most rapidly 
    changing location in memory. This difference represents a great potential for confusion.
"""
print(array[0,2])
print(array[0][2])

Elemento in posizione 2: 2
Elemento in posizione -2: 18
Matrice 5x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Elemento in posizione (4,2): 18
Elemento in posizione (3,-2): 14
array[0]: [0 1 2 3]
array[-1]: [16 17 18 19]
array[2][1]: 9
2
2


In [5]:
"""
OTHER INDEXING OPTIONS

    It is possible to slice and stride arrays to extract arrays of the same number of dimensions, 
    but of different sizes than the original. The slicing and striding works exactly the same way 
    it does for lists and tuples except that they can be applied to multiple dimensions as well. 
    A few examples illustrates best:
"""
array = np.arange(20)
print('array:', array)
print('array[2:5]:', array[2:5])
print('array [:-7]', array[:-7])
print('array [1:10:2]', array[1:10:2])
"""
    Note that slices of arrays do not copy the internal array data but also produce new 
    views of the original data. It is possible to index arrays with other arrays for the
    purposes of selecting lists of values out of arrays into new arrays. 
    There are two different ways of accomplishing this. One uses one or more arrays of index values. 
    The other involves giving a boolean array of the proper shape to indicate the values to be selected. 
    Index arrays are a very powerful tool that allow one to avoid looping over individual elements
    in arrays and thus greatly improve performance.It is possible to use special features 
    to effectively increase the number of dimensions in an array through indexing so the resulting 
    array aquires the shape needed for use in an expression or with a specific function.
"""
array2 = np.arange(35).reshape(5,7)
print('array2:\n', array2)
print('array2[1:5:2, ::3]:\n', array2[1:5:2, ::3])
print('array2[::2]\n', array2[::2])
print('array2:[1:5,1:2]\n', array2[1:5,1:2])

array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
array[2:5]: [2 3 4]
array [:-7] [ 0  1  2  3  4  5  6  7  8  9 10 11 12]
array [1:10:2] [1 3 5 7 9]
array2:
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
array2[1:5:2, ::3]:
 [[ 7 10 13]
 [21 24 27]]
array2[::2]
 [[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]]
array2:[1:5,1:2]
 [[ 8]
 [15]
 [22]
 [29]]


In [21]:
"""
INDEX ARRAY
    NumPy arrays may be indexed with other arrays (or any other sequence- like object that can be 
    converted to an array, such as lists, with the exception of tuples; 
    see the end of this document for why this is). The use of index arrays ranges from simple, 
    straightforward cases to complex, hard-to-understand cases. For all cases of index arrays, 
    what is returned is a copy of the original data, not a view as one gets for slices.

    Index arrays must be of integer type. Each value in the array indicates which value in 
    the array to use in place of the index. To illustrate:
"""
array = np.arange(10,1,-1)
print('array:', array)
second_array = np.array([3,3,1,8,])
print('array[np.array([3, 3, 1, 8]): ',array[second_array])
"""
    The index array consisting of the values 3, 3, 1 and 8 correspondingly create 
    an array of length 4 (same as the index array) where each index is replaced by the value the index
    array has in the array being indexed.

    Negative values are permitted and work as they do with single indices or slices:
"""


array: [10  9  8  7  6  5  4  3  2]
array[np.array([3, 3, 1, 8]):  [7 7 9 2]


'\n    The index array consisting of the values 3, 3, 1 and 8 correspondingly create \n    an array of length 4 (same as the index array) where each index is replaced by the value the index\n    array has in the array being indexed.\n\n    Negative values are permitted and work as they do with single indices or slices:\n'